### ISSUE TITLE
Cannot enable WMS layers in mobile browser

### ISSUE THREAD

**Issue by penpendede** [KlausBenndorf/guide4you#311] opened 2018-05-22 10:01 UTC
As far as desktop browsers are concerned, WMS layer selection works fine. However, using mobile browsers there is no reaction to the touch of the corresponding layer selection button. The issue exclusively occurs with WMS, there is no similar issue with WMTS. Also, it does not occur when you set up your mobile browser to display a desktop version of the page. I suspect some kind of event handling issue.

Moreover the WMS selection buttons don't display in the same manner as the other layer selection buttons - while the base font face is the same, it is a light one in contrast to being a bold one for the other buttons plus the text is not centered vertically.

It may therefore well be that these buttons lack a class and for this reason misbehave (supposing event handlers are added by class).

**Comment by simonseyock** [comment] 2018-05-24 11:45
The LayerSelector is quite messy at the moment. I am thinking about a smaller or bigger rework of the whole thing. This functionality is currently supported by the Layerselector:

- One Layer can corresponds to one button that toggles visibility.
- A layer group can correspond to category button. A click on the category button does normally collapse or expand all contained layers.
- A category button can be separated into two buttons. Than the second button does activate/deactivate all buttons.
- It is possible to combine multiple layers into one button.
- A WMS Layer can be shown as different buttons that activate different layers in the server request.
- A WMS Layer can have an info-toggle button that toggles the get feature info capabilities.
- If a WMS Layer is shown as different buttons, it can have a category button.
- Activation of a baselayer deactivates other baselayers (not neccessarily a feature of the layerselector)
- A certain layer button can get a special class name given through the config (i.e. for coloring).
- A click on a layer can open an info window.
- There exists a mobile view.

Ideas:

Stronger separation of the actual view and the building. That means having classes category and button that provide all needed events for all uses cases. This would separate the view concerns better from the classes used behind.

**Comment by SamOxyPlot** [comment] 2018-05-24 12:18
Please also note that since version 2.10.2 there is a problem regarding the deactivation of an active layer from a desktop or mobile device compared to the previous version.
Clicking an inactive layer does work!

I think the problem is related to commit **wms layerselector button** 6e95f923366013c8f9ac40129e60cbe62e66826e

Thanks in advance!

**Comment by simonseyock** [comment] 2018-05-24 14:34
@SamOxyPlot I don't exactly understand your problem. Please provide an example to reproduce the bug.

**Comment by simonseyock** [comment] 2018-05-28 12:21
Fixed by f38ee205477df341f5d97e168478adf4a704edbe

**Closed as completed by simonseyock** 2018-05-28 12:21 UTC
Labels: bug
